spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/tracking
    username: tracking
    password: tracking
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    virtual-host: /
    queue-name: tracking-exchange

clients:
  vehicles:
    base_path: http://localhost:8081
  telemetry_profile:
    base_path: http://localhost:8082
