# Build the application using Gradle
FROM maven:jdk17 as builder
WORKDIR /app
COPY . .
RUN ./mvnw install

# Use OpenJDK 11 JRE slim as the base image
FROM openjdk:17-alpine

COPY target/*.jar /app/app.jar
WORKDIR /app

CMD ["java", "-jar", "app.jar"]
