# Build the application using Gradle
FROM openjdk:17-jdk-slim-buster as builder
RUN apt-get update -y
RUN apt-get install -y binutils
WORKDIR /app
COPY . .
RUN ./mvnw install

# Use OpenJDK 11 JRE slim as the base image
FROM openjdk:17-alpine

COPY --from=builder target/*.jar /app/app.jar
WORKDIR /app

CMD ["java", "-jar", "app.jar"]
