version: "3.5"
networks:
  ipl:
    driver: bridge

services:
  postgres_vehicles:
    image: postgres:14-alpine
    container_name: postgres_vehicles
    restart: always
    environment:
        - POSTGRES_DB=vehicle
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - ipl

  vehicles_api:
    depends_on:
      - postgres_vehicles
    build: ./
    entrypoint: ./entrypoint.sh
    ports:
      - "5000:5000"
    networks:
      - ipl

