version: "3.5"
networks:
  ipl:
    driver: bridge

services:
  tracking:
    image: tracking
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracking
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_tracking_db:5432/tracking
      - SPRING_DATASOURCE_USERNAME=tracking
      - SPRING_DATASOURCE_PASSWORD=tracking
      - SPRING_RABBITMQ_HOST=ipl-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
      - SPRING_RABBITMQ_QUEUE_NAME=tracking-exchange
    depends_on:
      - ipl-rabbitmq
      - postgres_tracking_db
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ipl

  postgres_tracking_db:
    image: postgres:14-alpine
    container_name: postgres_tracking_db
    restart: always
    environment:
      - POSTGRES_DB=tracking
      - POSTGRES_USER=tracking
      - POSTGRES_PASSWORD=tracking
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    networks:
      - ipl

  ipl-rabbitmq:
    image: rabbitmq:3-management
    container_name: ipl-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
      - ipl